# Generated by Django 3.1.3 on 2020-11-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='selected_option',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
    ]
